openapi: 3.0.4
info:
  title: SnapD REST API
  license:
    name: "GNU GPL-v3"
    url: https://www.gnu.org/licenses/gpl-3.0.en.html
  version: v2
  description: |-
    The official OpenAPI 3.x specification for the SnapD REST API.
    This specification provides a modern, maintainable, and machine-readable definition of the API,
    serving as a single source of truth for documentation, client generation, and testing.

servers:
  - url: http+unix://run/snapd.socket/v2
    description: Local snapd socket access

tags:
  - name: Aliases
    description: Manage application command aliases.
  - name: Apps
    description: Listing and managing applications and thier attributes.
  - name: Assertions
    description: Listing and managing assertion types.
  - name: Async
    description: Endpoints not waiting for the operation to complete.
  - name: Authentication
    description: Endpoints relating to authenticating with the store.
  - name: Changes
    description: Monitoring the progress of asynchronous background operations.
  - name: Interfaces
    description: Managing interface connections, and thier metadata.
  - name : Macaroon
    description: Endpoints requiring Macaroon authentication.
  - name: Open
    description: Endpoints that require no authentication.
  - name: Quotas
    description: Managing resource quota groups.
  - name: Root
    description: Requires root access.
  - name: Snap Configuration
    description: Getting and setting configuration options on snaps and the system.
  - name: Snaps
    description: Installing, removing, and managing the lifecycle of snaps.
  - name: Snapshots
    description: Manipulate, import or export snapshots.
  - name: Store
    description: Finding snaps and interacting with the store.
  - name: Sync
    description: Endpoints waiting for the operation to complete.
  - name: System
    description: Core daemon status, list and activate recovery systems.
  - name: Users
    description: Creating, manage, and query user accounts.
  - name: Validation Sets
    description: List an manage validation sets.

paths:
  /aliases:
    $ref: './v2/paths/aliases.yaml'
  /apps:
    $ref: './v2/paths/apps.yaml'
  /assertions:
    $ref: './v2/paths/assertions.yaml'
  /assertions/{assertionType}:
    $ref: './v2/paths/assertions-type.yaml'
  /changes:
    $ref: './v2/paths/changes.yaml'
  /changes/{id}:
    $ref: './v2/paths/changes-id.yaml'
  /cohorts:
    $ref: './v2/paths/cohorts.yaml'
  /confdb/{account}/{confdb-schema}/{view}:
    $ref: './v2/paths/confdb.yaml'
  /connections:
    $ref: './v2/paths/connections.yaml'
  /find:
    $ref: './v2/paths/find.yaml'
  /icons/{name}/icon:
    $ref: './v2/paths/icons-name.yaml'
  /interfaces:
    $ref: './v2/paths/interfaces.yaml'
  /interfaces/requests/prompts:
    $ref: './v2/paths/prompts.yaml'
  /interfaces/requests/prompts/{id}:
    $ref: './v2/paths/prompts-id.yaml'
  /interfaces/requests/rules:
    $ref: './v2/paths/rules.yaml'
  /interfaces/requests/rules/{id}:
    $ref: './v2/paths/rules-id.yaml'
  /login:
    $ref: './v2/paths/login.yaml'
  /logout:
    $ref: './v2/paths/logout.yaml'
  /logs:
    $ref: './v2/paths/logs.yaml'
  /model:
    $ref: './v2/paths/model.yaml'
  /model/serial:
    $ref: './v2/paths/model-serial.yaml'
  /notices:
    $ref: './v2/paths/notices.yaml'
  /quotas:
    $ref: './v2/paths/quotas.yaml'
  /quotas/{group-name}:
    $ref: './v2/paths/quotas-name.yaml'
  /sections:
    $ref: './v2/paths/sections.yaml'
  /snapctl:
    $ref: './v2/paths/snapctl.yaml'
  /snaps:
    $ref: './v2/paths/snaps.yaml'
  /snaps/{name}:
    $ref: './v2/paths/snaps-name.yaml'
  /snaps/{name}/conf:
    $ref: './v2/paths/snaps-name-conf.yaml'
  /snapshots:
    $ref: './v2/paths/snapshots.yaml'
  /snapshots/{set-id}/export:
    $ref: './v2/paths/snapshots-set-id-export.yaml'
  /system-info:
    $ref: './v2/paths/system-info.yaml'
  /system-recovery-keys:
    $ref: './v2/paths/system-recovery-keys.yaml'
  /systems:
    $ref: './v2/paths/systems.yaml'
  /systems/{label}:
    $ref: './v2/paths/systems-label.yaml'
  /users:
    $ref: './v2/paths/users.yaml'
  /validation-sets:
    $ref: './v2/paths/validation-sets.yaml'
  /validation-sets/{account-id}/{name}:
    $ref: './v2/paths/validation-sets-name.yaml'
  /warnings:
    $ref: './v2/paths/warnings.yaml'

components:
  securitySchemes:
    macaroonAuth:
      $ref: './v2/components/security/Macaroon.yaml'
    rootAuth:
      $ref: './v2/components/security/Root.yaml'
  responses:
    Accepted:
      $ref: './v2/components/responses/Accepted.yaml'
    BadRequest:
      $ref: './v2/components/responses/BadRequest.yaml'
    NotFound:
      $ref: './v2/components/responses/NotFound.yaml'
  parameters:
    UserId:
      $ref: './v2/components/parameters/UserId.yaml'
  schemas:                                                    # Rules are technically schema
    App:
      $ref: './v2/components/schemas/App.yaml'
    AsyncOperation:
      $ref: './v2/components/schemas/AsyncOperation.yaml'
    Change:
      $ref: './v2/components/schemas/Change.yaml'
    Connection:
      $ref: './v2/components/schemas/Connection.yaml'
    ConnectionEndpoint:
      $ref: './v2/components/schemas/ConnectionEndpoint.yaml'
    ConnectionStatus:
      $ref: './v2/components/schemas/ConnectionStatus.yaml'
    InstalledSnap:
      $ref: './v2/components/schemas/InstalledSnap.yaml'
    MediaItem:
      $ref: './v2/components/schemas/MediaItem.yaml'
    Notice:
      $ref: './v2/components/schemas/Notice.yaml'
    Prompt:
      $ref: './v2/components/schemas/Prompt.yaml'
    PromptReply:
      $ref: './v2/components/schemas/PromptReply.yaml'
    Publisher:
      $ref: './v2/components/schemas/Publisher.yaml'
    QuotaGroup:
      $ref: './v2/components/schemas/QuotaGroup.yaml'
    Rule:
      $ref: './v2/components/rules/Rule.yaml'
    RuleActionAdd:
      $ref: './v2/components/rules/RuleActionAdd.yaml'
    RuleActionPatch:
      $ref: './v2/components/rules/RuleActionPatch.yaml'
    RuleActionRemove:
      $ref: './v2/components/rules/RuleActionRemove.yaml'
    RuleActionRemoveById:
      $ref: './v2/components/rules/RuleActionRemoveById.yaml'
    Snap:
      $ref: './v2/components/schemas/Snap.yaml'
    Snapshot:
      $ref: './v2/components/schemas/Snapshot.yaml'
    SnapshotSet:
      $ref: './v2/components/schemas/SnapshotSet.yaml'
    StandardError:
      $ref: './v2/components/schemas/StandardError.yaml'
    System:
      $ref: './v2/components/schemas/System.yaml'
    SystemInfo:
      $ref: './v2/components/schemas/SystemInfo.yaml'
    Task:
      $ref: './v2/components/schemas/Task.yaml'
    User:
      $ref: './v2/components/schemas/User.yaml'
