# SPDX-License-Identifier: GPL-3.0
# SPDX-FileCopyrightText: Canonical Ltd

openapi: 3.0.3
info:
  title: Snapd REST API
  license:
    name: GPL-3.0
    url: https://www.gnu.org/licenses/gpl-3.0.txt
  version: '0.1'
  description: |
        The REST API provides access to snapd's state and many of its key functions,
        as listed below.

        For general information on how to use the API, including how to access it,
        its requests and responses, results fields and error types, see [Using the
        REST API](https://snapcraft.io/docs/using-the-api).
servers:
  - url: unix:///run/snapd.socket
    description: |-
      Local snapd socket access. Unless otherwise specified, routes appear on
      this socket.
  - url: unix:///run/snapd-snap.socket
    description: Snapd socket access for snaps
externalDocs:
  url: https://snapcraft.io/docs
  description: Snap and Snapcraft documentation

tags:
  - name: Aliases
    description: Manage application command aliases.
  - name: Assertions
    description: List and add assertion types.
  - name: Asynchronous
    description: Return the reference to a change that will occur in the background.
  - name: AuthenticationRequired
    description: Access is restricted to the root user.
  - name: Changes
    description: Interact with changes.
  - name: Interfaces
    description: Display and manage interactions between snaps.
  - name: Notices
    description: Interact with notices.
  - name: OpenAccess
    description: Do not require the user to authenticate.
  - name: Snaps
    description: Interact with snaps.
  - name: Store
    description: Interact with the store.
  - name: Synchronous
    description: Return the complete response synchronously.
  - name: Warnings
    description: Retrieve recorded warnings.

components:
  securitySchemes:
    PeerAuth:
      $ref: './v2/components/security/PeerAuth.yaml'

  responses:
    Accepted:
      $ref: './v2/components/responses/Accepted.yaml'
    AccessDenied:
      $ref: './v2/components/responses/AccessDenied.yaml'
    BadRequest:
      $ref: './v2/components/responses/BadRequest.yaml'
    Conflict:
      $ref: './v2/components/responses/Conflict.yaml'
    Forbidden:
      $ref: './v2/components/responses/Forbidden.yaml'
    InternalError:
      $ref: './v2/components/responses/InternalError.yaml'
    NotAllowed:
      $ref: './v2/components/responses/NotAllowed.yaml'
    NotFound:
      $ref: './v2/components/responses/NotFound.yaml'

  schemas:
    ConflictError:
      $ref: './v2/components/errors/ConflictError.yaml'
    InternalServerError:
      $ref: './v2/components/errors/InternalServerError.yaml'
    MalformedRequestError:
      $ref: './v2/components/errors/MalformedRequestError.yaml'
    NotAllowedError:
      $ref: './v2/components/errors/NotAllowedError.yaml'
    SnapNotInstalledError:
      $ref: './v2/components/errors/SnapNotInstalledError.yaml'

    Activator:
      $ref: './v2/components/schemas/Activator.yaml'
    App:
      $ref: './v2/components/schemas/App.yaml'
    AppActionBase:
      $ref: './v2/components/schemas/AppActionBase.yaml'
    AppActionRestart:
      $ref: './v2/components/schemas/AppActionRestart.yaml'
    AppActionStart:
      $ref: './v2/components/schemas/AppActionStart.yaml'
    AppActionStop:
      $ref: './v2/components/schemas/AppActionStop.yaml'
    AssertionResult:
      $ref: './v2/components/schemas/AssertionResult.yaml'
    Change:
      $ref: './v2/components/schemas/Change.yaml'
    Connection:
      $ref: './v2/components/schemas/Connection.yaml'
    ConnectionStatus:
      $ref: './v2/components/schemas/ConnectionStatus.yaml'
    FindResult:
      $ref: './v2/components/schemas/FindResult.yaml'
    LegacyInterfaceObject:
      $ref: './v2/components/schemas/LegacyInterfaceObject.yaml'
    ModernInterfaceObject:
      $ref: './v2/components/schemas/ModernInterfaceObject.yaml'
    Links:
      $ref: './v2/components/schemas/Links.yaml'
    Log:
      $ref: './v2/components/schemas/Log.yaml'
    Media:
      $ref: './v2/components/schemas/Media.yaml'
    Notice:
      $ref: './v2/components/schemas/Notice.yaml'
    Plug:
      $ref: './v2/components/schemas/Plug.yaml'
    PlugRef:
      $ref: './v2/components/schemas/PlugRef.yaml'
    Progress:
      $ref: './v2/components/schemas/Progress.yaml'
    Publisher:
      $ref: './v2/components/schemas/Publisher.yaml'
    QuotaGroup:
      $ref: './v2/components/schemas/QuotaGroup.yaml'
    Slot:
      $ref: './v2/components/schemas/Slot.yaml'
    SlotRef:
      $ref: './v2/components/schemas/SlotRef.yaml'
    Snap:
      $ref: './v2/components/schemas/Snap.yaml'
    Snapshot:
      $ref: './v2/components/schemas/Snapshot.yaml'
    SnapshotSet:
      $ref: './v2/components/schemas/SnapshotSet.yaml'
    StoreCategory:
      $ref: './v2/components/schemas/StoreCategory.yaml'
    SystemInfo:
      $ref: './v2/components/schemas/SystemInfo.yaml'
    Task:
      $ref: './v2/components/schemas/Task.yaml'
    Warning:
      $ref: './v2/components/schemas/Warning.yaml'

paths:
  /v2/aliases:
    $ref: './v2/paths/aliases.yaml'
  /v2/apps:
    $ref: './v2/paths/apps.yaml'
  /v2/assertions:
    $ref: './v2/paths/assertions.yaml'
  /v2/assertions/{assertionType}:
    $ref: './v2/paths/assertions-type.yaml'
  /v2/changes:
    $ref: './v2/paths/changes.yaml'
  /v2/changes/{id}:
    $ref: './v2/paths/changes-id.yaml'
  /v2/cohorts:
    $ref: './v2/paths/cohorts.yaml'
  /v2/connections:
    $ref: './v2/paths/connections.yaml'
  /v2/find:
    $ref: './v2/paths/find.yaml'
  /v2/icons/{name}/icon:
    $ref: './v2/paths/icons-name.yaml'
  /v2/interfaces:
    $ref: './v2/paths/interfaces.yaml'
  /v2/login:
    $ref: './v2/paths/login.yaml'
  /v2/logout:
    $ref: './v2/paths/logout.yaml'
  /v2/logs:
    $ref: './v2/paths/logs.yaml'
  /v2/model:
    $ref: './v2/paths/model.yaml'
  /v2/model/serial:
    $ref: './v2/paths/serial.yaml'
  /v2/notices:
    $ref: './v2/paths/notices.yaml'
  /v2/notices/{id}:
    $ref: './v2/paths/notices-id.yaml'
  /v2/quotas:
    $ref: './v2/paths/quotas.yaml'
  /v2/quotas/{group-name}:
    $ref: './v2/paths/quotas-name.yaml'
  /v2/sections:
    $ref: './v2/paths/sections.yaml'
  /v2/snapctl:
    $ref: './v2/paths/snapctl.yaml'
  /v2/snapshots:
    $ref: './v2/paths/snapshots.yaml'
  /v2/snapshots/{set-id}/export:
    $ref: './v2/paths/snapshots-export.yaml'
  /v2/system-info:
    $ref: './v2/paths/system-info.yaml'
  /v2/validation-sets:
    $ref: './v2/paths/validation-sets.yaml'
  /v2/validation-sets/{account-id}/{name}:
    $ref: './v2/paths/validation-sets-name.yaml'
  /v2/warnings:
    $ref: './v2/paths/warnings.yaml'
