name: Build and Push Docker Image

on:
  push:
    branches:
      - main

# Add this permissions block
permissions:
  contents: read
  packages: write # Required to push to GitHub Packages/Container Registry

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # New step to extract Docker metadata (like tags)
      - name: Extract Docker metadata
        id: meta # Give this step an ID to reference its outputs
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Base image name

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          # Use the tags generated by the metadata-action step
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}